inherit_from: .rubocop_todo.yml
plugins: rubocop-rspec

AllCops:
  NewCops: enable
  Include:
    - 'lib/**/*'
    - 'spec/**/*'
  Exclude:
    - 'vendor/**/*'
    - 'integration/**/vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'pkg/**/*'
    - 'spec/fixtures/**/*'

Naming/FileName:
  Exclude:
    - 'lib/jekyll-meta.rb'
