# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jekyll-meta', path: '../../', group: :jekyll_plugins

gem 'jekyll', ENV['JEKYLL_VERSION'] if ENV['JEKYLL_VERSION']

# Required in Ruby 3.4+ when Jekyll < 4.4
gem 'base64'
gem 'bigdecimal'
gem 'csv'
gem 'logger'

# Required in Ruby 3.3.4 when Jekyll == 3.10
gem 'kramdown-parser-gfm'
