name: Label PR
on:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read

jobs:
  pr-labeler:
    permissions:
      contents: read # for TimonVS/pr-labeler-action to read config file
      pull-requests: write # for TimonVS/pr-labeler-action to add labels in PR
      issues: write # for TimonVS/pr-labeler-action to create labels
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v5
        with:
          repo-token: ${{ github.token }}
          configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
