name: Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: RuboCop Lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: bundle install

      - name: Run RuboCop
        run: bundle exec rubocop
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.3.4, 3.4]
        jekyll: [3.10.0, 4.3.4, 4.4.0, 4.4.1]
    name: Ruby ${{ matrix.ruby }} / Jekyll ${{ matrix.jekyll }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      
      - name: Install dependencies
        run: bundle install
        env:
          JEKYLL_VERSION: ${{ matrix.jekyll }}

      - name: Run tests
        run: bundle exec rspec

      - name: Show installed gems
        if: failure()
        run: bundle list

  integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.3.4, 3.4]
    name: Integration tests ${{ matrix.ruby }} 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Bats
        run: |
          git clone https://github.com/bats-core/bats-core.git
          sudo ./bats-core/install.sh /usr/local
      
      - name: Run tests
        run: bats integration

  required-tests:
    name: Check required tests passed
    runs-on: ubuntu-latest
    needs: [lint, test, integration]
    if: ${{ success() }}  # Only runs if all `needs` succeeded
    
    steps:
      - name: Confirm all dependencies succeeded
        run: echo "All matrix and lint tests passed successfully."
